name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Run release-please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json

  build-and-upload:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    env:
      RUST_BACKTRACE: 1
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        target: wasm32-wasip1

    - name: Build WASM plugin
      run: cargo build --target wasm32-wasip1 --release

    - name: Prepare release assets
      run: |
        mkdir -p release-assets
        cp target/wasm32-wasip1/release/zsm.wasm release-assets/
        
        # Create checksums
        cd release-assets
        sha256sum zsm.wasm > checksums.txt

    - name: Upload release assets
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ needs.release-please.outputs.tag_name }}
        files: |
          release-assets/zsm.wasm
          release-assets/checksums.txt
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}